version: "3.9"
services: 
  mysql:
    image: mysql
    volumes:
      - ./conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somethinghard
      MYSQL_USER: thrift
      MYSQL_PASSWORD: hhrifttunter
      MYSQL_DATABASE: thrifthunter
