CREATE TABLE item (
	id INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	type  TINYINT(2) NOT NULL FOREIGN KEY REFERENCES item(id),
	price INT(9) NOT NULL,
	seller VARCHAR(100) NOT NULL,
	location VARCHAR(100) NOT NULL,
	link VARCHAR(100) NOT NULL,
	description VARCHAR(255) NOT NULL,
	status BOOL,
	created_at TIMESTAMP
)

CREATE TABLE item_type (
	id TINYINT(2) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20) NOT NULL
)

CREATE TABLE image_item (
	link VARCHAR(100) NOT NULL  PRIMARY KEY,
	id INT(7) UNSIGNED NOT NULL FOREIGN KEY REFERENCES item(id)
)
