CREATE TABLE item_type (
	id TINYINT(2) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20) NOT NULL
);

CREATE TABLE item (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	type  TINYINT(2) UNSIGNED NOT NULL,
	price INT(9) NOT NULL,
	seller VARCHAR(100) NOT NULL,
	location VARCHAR(100) NOT NULL,
	link VARCHAR(100) NOT NULL,
	description VARCHAR(255) NOT NULL,
	status BOOLEAN,
	created_at TIMESTAMP,
	FOREIGN KEY (type) REFERENCES item_type(id)
);

CREATE TABLE image_item (
	link VARCHAR(100) NOT NULL  PRIMARY KEY,
	id INT(11) UNSIGNED NOT NULL,
    	FOREIGN KEY (id) REFERENCES item(id)
);
