CREATE TABLE users (
	id INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(50) NOT NULL UNIQUE KEY,
	password VARCHAR(50) NOT NULL,
	phone VARCHAR(14) NOT NULL,
	username VARCHAR(50) NOT NULL,
	created_at TIMESTAMP
)
